---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Simple API"
paths:
  /:
    get:
      operationId: "controllers.hello_world.say_hi"
      parameters: []
      responses:
        200:
          description: "OK"

definitions: {}
